// Fitter Design System v1 — Tailwind 매핑
// tailwind.config.js 의 theme.extend 에 펼쳐 넣는다. 값은 CSS 변수를 가리키므로 다크모드가 자동으로 따라온다.
module.exports = {
  darkMode: ['class', '[data-theme="dark"]'],
  theme: {
    extend: {
      colors: {
        primary: {
          50: 'var(--color-primary-50)',
          100: 'var(--color-primary-100)',
          200: 'var(--color-primary-200)',
          300: 'var(--color-primary-300)',
          400: 'var(--color-primary-400)',
          500: 'var(--color-primary-500)',
          600: 'var(--color-primary-600)',
          700: 'var(--color-primary-700)',
          800: 'var(--color-primary-800)',
        },
        secondary: {
          100: 'var(--color-secondary-100)',
          300: 'var(--color-secondary-300)',
          500: 'var(--color-secondary-500)',
          600: 'var(--color-secondary-600)',
        },
        bg: 'var(--color-bg)',
        'bg-subtle': 'var(--color-bg-subtle)',
        'bg-sunken': 'var(--color-bg-sunken)',
        surface: 'var(--color-surface)',
        'surface-hover': 'var(--color-surface-hover)',
        fg: 'var(--color-text-primary)',
        'fg-secondary': 'var(--color-text-secondary)',
        'fg-tertiary': 'var(--color-text-tertiary)',
        'fg-inverse': 'var(--color-text-inverse)',
        success: 'var(--color-success)',
        'success-bg': 'var(--color-success-bg)',
        warning: 'var(--color-warning)',
        'warning-bg': 'var(--color-warning-bg)',
        danger: 'var(--color-danger)',
        'danger-bg': 'var(--color-danger-bg)',
        border: 'var(--color-border)',
        'border-strong': 'var(--color-border-strong)',
      },
      spacing: {
        1: 'var(--space-1)',
        2: 'var(--space-2)',
        3: 'var(--space-3)',
        4: 'var(--space-4)',
        5: 'var(--space-5)',
        6: 'var(--space-6)',
        8: 'var(--space-8)',
        10: 'var(--space-10)',
        12: 'var(--space-12)',
        16: 'var(--space-16)',
      },
      borderRadius: {
        sm: 'var(--radius-sm)',
        md: 'var(--radius-md)',
        lg: 'var(--radius-lg)',
        xl: 'var(--radius-xl)',
        full: 'var(--radius-full)',
      },
      boxShadow: { 1: 'var(--shadow-1)', 2: 'var(--shadow-2)', 3: 'var(--shadow-3)' },
      fontFamily: {
        sans: ['Pretendard Variable', 'Pretendard', '-apple-system', 'system-ui', 'sans-serif'],
        mono: ['ui-monospace', 'SFMono-Regular', 'SF Mono', 'Menlo', 'monospace'],
      },
      fontSize: {
        display: 'var(--text-display)',
        h1: 'var(--text-h1)',
        h2: 'var(--text-h2)',
        h3: 'var(--text-h3)',
        body: 'var(--text-body)',
        caption: 'var(--text-caption)',
      },
      height: {
        'ctl-sm': 'var(--control-h-sm)',
        'ctl-md': 'var(--control-h-md)',
        'ctl-lg': 'var(--control-h-lg)',
        touch: 'var(--control-h-touch)',
      },
      screens: { md: '768px', lg: '1024px', xl: '1280px' },
    },
  },
};
